name: 'Push Alert'
description: 'Alert When push without review'
author: 'Shiqi Yang'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  slack-endpoint:
    description: 'slack notification endpoint, can be passed in using {{ secrets.SLACK_NOTIFY_ENDPOINT }}'
    required: true
  slack-channel:
    description: 'slack channel name to notify'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'